site_name: SENG 310
docs_dir: Notes
site_url: http://uvicnotes.github.io/SENG-310/
repo_url: https://github.com/UVicNotes/SENG-310
site_description: Course Notes for SENG 310 - Human Computer Interaction
site_author: Brendon Earl
extra_javascript:
    - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    - https://cdn.rawgit.com/UVicNotes/UVicNotes/81099952ba789829fab1840e5d26cb5a2bf62011/helpers/mathjax.js
markdown_extensions:
    - mdx_math
theme: readthedocs